/**
 * 410 Gone — the retired `/feeds/*` "Resource Hub" (2026-08-17). Enforced in
 * `src/proxy.ts`.
 *
 * 196 pages (~3,800 words each) generated by a third-party AI SEO vendor on the
 * seqtek.com domain, two-thirds of every URL the old site published. Not
 * migrated: it ranked SEQTEK #1 above Accenture, BCG, Deloitte and McKinsey on
 * SEQTEK's own domain, targeted markets SEQTEK does not serve ("Business
 * Consulting Services in Fort Wayne, IN"), and is the shape Google's
 * scaled-content-abuse policy is aimed at — which acts site-level, not
 * page-level.
 *
 * 410 rather than 301 to /insights ON PURPOSE: a 301 would name Insights the
 * successor to that topical footprint and import any penalty attached to it.
 */

export const RETIRED_PREFIXES: readonly string[] = ['/feeds']

export function isRetiredPath(pathname: string): boolean {
  return RETIRED_PREFIXES.some((prefix) => pathname === prefix || pathname.startsWith(`${prefix}/`))
}

/** Inline and dependency-free, same rationale as MAINTENANCE_HTML in proxy.ts. */
export const GONE_HTML = `<!doctype html>
<html lang="en"><head><meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="robots" content="noindex" />
<title>SEQTEK — Page removed</title>
<style>body{font-family:system-ui,sans-serif;margin:0;min-height:100vh;display:flex;align-items:center;justify-content:center;background:#0b1220;color:#e6edf6;text-align:center;padding:1.5rem}main{max-width:34rem}h1{font-size:1.5rem;margin:0 0 .75rem}p{color:#9fb0c3;line-height:1.6;margin:0 0 1.25rem}a{color:#88c45f}ul{list-style:none;padding:0;margin:0;display:flex;gap:1.5rem;justify-content:center;flex-wrap:wrap}</style>
</head><body><main>
<h1>This page has been removed</h1>
<p>It was part of a resource library we have retired. Our current writing and client work live here:</p>
<ul>
<li><a href="/insights">Insights</a></li>
<li><a href="/case-studies">Case studies</a></li>
<li><a href="/services">Services</a></li>
<li><a href="/contact">Contact</a></li>
</ul>
</main></body></html>`
