# SEQTEK website production image — multi-stage build for Next.js +
# Payload on Node 24 Alpine. Productionized from the D-13 spike
# Dockerfile per spec 002 T018: npm-only path, non-root runtime user,
# HEALTHCHECK directive, no .git/.env/specs/docs in the image.

# Pin to a known Node 24 patch + upgrade npm to the version local dev
# uses. The lockfile is generated by local npm 11.12.1; older or newer
# npm versions resolve peer/optional dep trees differently, which
# breaks `npm ci`. Both the bundled npm in `node:24-alpine` (11.13.0)
# and `node:24.11.1-alpine` (11.6.2) drift from local; explicit upgrade
# below normalizes the resolver.
FROM node:24.11.1-alpine AS base
RUN npm install -g npm@11.12.1

# ---- deps stage: install production + build dependencies ----
FROM base AS deps
# libc6-compat is needed by some native modules (sharp etc.) on Alpine.
# https://github.com/nodejs/docker-node/tree/main#nodealpine
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Copy `.npmrc` too — the repo sets `legacy-peer-deps=true`, which the
# lockfile was generated against. Without it, npm tries to install
# peer deps the lockfile correctly omits, and `npm ci` fails the
# integrity check.
COPY package.json package-lock.json .npmrc ./
RUN npm ci

# ---- builder stage: compile the Next.js standalone output ----
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Disable Next.js telemetry during the build.
ENV NEXT_TELEMETRY_DISABLED=1

RUN npm run build

# ---- runner stage: slim production image ----
FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Non-root user matching the spike convention (uid/gid 1001).
RUN addgroup --system --gid 1001 nodejs \
  && adduser --system --uid 1001 nextjs

# `wget` is in alpine's base; we use it for the HEALTHCHECK below.
# `tini` provides proper signal handling so `docker stop` reaches the
# Node process cleanly (avoids 10s SIGKILL on rolling refresh).
RUN apk add --no-cache tini

# Create the prerender cache dir with the right ownership.
RUN mkdir .next && chown nextjs:nodejs .next

# Copy the standalone server + static assets.
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

# VALIDATION PERIOD: include the full node_modules + source + tsconfig
# + payload-types so `npx payload migrate:fresh` can run as a one-shot
# DB bootstrap on container start. Without this, the standalone build
# strips the Payload CLI which is needed to create the initial DB
# schema. Phase 5.5 polish will:
#  - Generate migration files via `npx payload migrate:create` at
#    build time (in the builder stage)
#  - Drop the runtime node_modules / src copy
#  - Run `npx payload migrate` (idempotent, no destructive fresh)
# This adds ~350 MB to the runtime image; acceptable for validation.
COPY --from=builder --chown=nextjs:nodejs /app/node_modules ./node_modules
COPY --from=builder --chown=nextjs:nodejs /app/src ./src
COPY --from=builder --chown=nextjs:nodejs /app/tsconfig.json ./tsconfig.json
COPY --from=builder --chown=nextjs:nodejs /app/next.config.ts ./next.config.ts
COPY --from=builder --chown=nextjs:nodejs /app/package.json ./package.json

USER nextjs

EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

HEALTHCHECK --interval=30s --timeout=10s --start-period=60s --retries=3 \
  CMD wget --quiet --tries=1 --spider http://localhost:3000/api/health || exit 1

ENTRYPOINT ["/sbin/tini", "--"]

# Run payload migrate (idempotent — only runs new migrations) before
# the server starts. Migration files live in src/migrations/ and are
# generated locally via `npx payload migrate:create` against the dev
# Postgres on :5433. New schema changes during development add new
# migration files; production deploys apply them in order.
CMD ["sh", "-c", "npx payload migrate && node server.js"]
