/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    caseStudies: CaseStudy;
    services: Service;
    industries: Industry;
    workshops: Workshop;
    teamMembers: TeamMember;
    partners: Partner;
    media: Media;
    navigation: Navigation;
    testimonials: Testimonial;
    categories: Category;
    locations: Location;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    caseStudies: CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    industries: IndustriesSelect<false> | IndustriesSelect<true>;
    workshops: WorkshopsSelect<false> | WorkshopsSelect<true>;
    teamMembers: TeamMembersSelect<false> | TeamMembersSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Standalone pages built from blocks, reached at the top level of the site like /our-story. Use one for anything that is not a post, a case study, a service or an industry.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * The name of this page. It becomes the browser tab title and the default search result headline.
   */
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  /**
   * The last part of the web address for this page, for example "about-us". Lowercase words joined by hyphens, no spaces. Changing it on something already published breaks every existing link to it.
   */
  slug: string;
  /**
   * Scheduling only. A date in the future forces this record back to draft, so it will not go live until that date passes and someone publishes it.
   */
  publishedAt?: string | null;
  /**
   * The page itself, built from blocks. Add a block for each band of content down the page; drag the handles to reorder.
   */
  layout?:
    | (
        | HeroBlock
        | ContentBlock
        | MediaTextBlock
        | ItemsBlock
        | ImageBlock
        | GalleryBlock
        | TableBlock
        | AccordionBlock
        | QuoteBlock
        | CtaBlock
        | CardsBlock
        | EmbedBlock
        | HubspotFormBlock
      )[]
    | null;
  /**
   * How this page looks in a Google result and when someone pastes its link into LinkedIn or Slack. Everything here is optional.
   */
  seo?: {
    /**
     * The blue headline in a Google result. Leave blank to use the page title above. "| SEQTEK" is appended automatically, so do not type it.
     */
    metaTitle?: string | null;
    /**
     * The gray summary under that headline, and the text on a shared link. Google truncates around 155 characters. Leave blank and every search result for this collection shows the same generic company tagline, so it is worth writing.
     */
    metaDescription?: string | null;
    /**
     * The picture that appears when someone shares this link on LinkedIn, Facebook or Slack. Landscape, at least 1200x630. Without one the shared link renders as text only.
     */
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  /**
   * "Split" sets the words beside a picture and suits most pages. "Cover" lays the words in white over a full-width photo, darkened so they stay readable; use it for the homepage or a campaign page. "With video" puts a video under the words. "Text only" is for a page with no picture at all.
   */
  variant: 'text-only' | 'split' | 'cover' | 'with-video';
  /**
   * The small line above the headline, in caps. Two or three words that say what kind of thing this is, e.g. "Case study".
   */
  eyebrow?: string | null;
  /**
   * The first thing a visitor reads on this page. Say what we do for them, not who we are.
   */
  headline: string;
  /**
   * One or two sentences under the headline. Optional.
   */
  subheadline?: string | null;
  /**
   * Shown only by the "Split" and "Cover" styles. "Split" sets it beside the words; "Cover" stretches it behind them, so pick a photo with quiet space where the words fall. Landscape, at least 2000px wide.
   */
  media?: (number | null) | Media;
  /**
   * Shown only by the "With video" style. Paste the player's EMBED address, not the page you watch on: https://www.youtube-nocookie.com/embed/ID or https://player.vimeo.com/video/ID. Anything else is dropped at render time and the hero shows no video at all.
   */
  videoUrl?: string | null;
  /**
   * Optional. Leave both fields empty and the hero renders without buttons.
   */
  primaryCta?: {
    /**
     * The words on the button. Two to four words reads best, e.g. "Book a call".
     */
    label?: string | null;
    /**
     * Where the button goes. A path on this site starts with a slash ("/contact"); an outside link needs the full https:// address.
     */
    url?: string | null;
    /**
     * How much weight the button carries: solid for the one thing you want clicked, outlined for a real but lesser option, text-only when it should not compete with the page.
     */
    variant?: ('primary' | 'secondary' | 'ghost') | null;
  };
  /**
   * Optional, and independent of the main button: fill in only this one and it is the only button the hero draws.
   */
  secondaryCta?: {
    /**
     * The words on the button. Two to four words reads best, e.g. "Book a call".
     */
    label?: string | null;
    /**
     * Where the button goes. A path on this site starts with a slash ("/contact"); an outside link needs the full https:// address.
     */
    url?: string | null;
  };
  /**
   * Left is the default and easiest to read. Center suits a short headline with no picture beside it.
   */
  alignment?: ('left' | 'center') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * Every image and file on the site. Upload once and reuse it anywhere, and write the alt text while you are here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * What this image shows, in a sentence, for someone using a screen reader. Describe the content, not the file: "Two engineers at a whiteboard", not "photo 1".
   */
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    mobile_webp?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    mobile_jpeg?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet_webp?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet_jpeg?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    desktop_webp?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    desktop_jpeg?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide_webp?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide_jpeg?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  /**
   * How wide the text runs. Standard is the comfortable reading width and is right nearly always; wide suits text with images or tables in it.
   */
  width?: ('narrow' | 'standard' | 'wide') | null;
  /**
   * The prose of this section. Use the slash menu to drop in a callout, a pull quote, an image or an FAQ between paragraphs.
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * The colour band behind this section. Alternate it with the sections around it.
   */
  background?: ('none' | 'subtle' | 'accent' | 'inverse') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaTextBlock".
 */
export interface MediaTextBlock {
  /**
   * The picture beside the text. Landscape or square.
   */
  media: number | Media;
  /**
   * On a phone the two stack in this order, so "Left" puts the image first and "Right" puts the text first. Alternate the side down a page of these so it does not read as a ladder.
   */
  mediaPosition: 'left' | 'right';
  /**
   * The words beside the image. Start with a short heading, then a paragraph or two.
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Optional. Appears under the text, e.g. "Read our story". Leave both fields empty for no button.
   */
  cta?: {
    /**
     * The words on the button. Two to four words reads best, e.g. "Book a call".
     */
    label?: string | null;
    /**
     * Where the button goes. A path on this site starts with a slash ("/contact"); an outside link needs the full https:// address.
     */
    url?: string | null;
  };
  /**
   * The colour band behind this section. Alternate it with the sections around it.
   */
  background?: ('none' | 'subtle' | 'accent' | 'inverse') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'media-text';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ItemsBlock".
 */
export interface ItemsBlock {
  /**
   * The line that introduces this section. Leave it blank to run the section without a heading.
   */
  heading?: string | null;
  /**
   * A sentence or two under the heading. Leave it blank to go straight to the content.
   */
  intro?: string | null;
  /**
   * Grid sets the items side by side, with as many columns as the count suits. A line runs them top to bottom joined by a rule, for steps or dates. A compact list is bullets, two columns on a wide screen. Tags are small chips, like a list of technologies.
   */
  layout?: ('grid' | 'line' | 'list' | 'tags') | null;
  /**
   * A large marker with each title. Numbers count in the order you arrange the items. "Your own" shows what you type on each item: a figure like "25+", a letter that spells a word down a line, or a year. Hidden for tags.
   */
  markers?: ('none' | 'numbers' | 'custom') | null;
  /**
   * Only for the grid. Plain reads like an index: a rule, a bold title, a few lines. Cards box each item, which suits items with a picture or a link.
   */
  style?: ('plain' | 'card') | null;
  /**
   * Add as many as the section needs. The layout adjusts to the count.
   */
  items: {
    /**
     * A few words. In a row of figures, this is what the figure counts, e.g. "years in Tulsa".
     */
    title: string;
    /**
     * Optional. One to three sentences under the title. Tags do not show it.
     */
    body?: string | null;
    /**
     * Shown large with the title: a figure like "25+", a letter, or a year. Shown while markers are set to "Your own".
     */
    marker?: string | null;
    /**
     * Optional picture above the title, landscape. Only the grid shows it.
     */
    image?: (number | null) | Media;
    /**
     * Optional. With an address, the title (or the tag) becomes a link. Add link text to also show a "link text →" line under the item; tags do not show it.
     */
    link?: {
      /**
       * E.g. "Read the case study". Leave it blank to link the title only.
       */
      label?: string | null;
      /**
       * Where it goes. A page on this site starts with a slash ("/services"); an outside link needs the full https:// address.
       */
      url?: string | null;
    };
    id?: string | null;
  }[];
  /**
   * The colour band behind this section. Alternate it with the sections around it.
   */
  background?: ('none' | 'subtle' | 'accent' | 'inverse') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'items';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlock".
 */
export interface ImageBlock {
  /**
   * Pick from Media, or upload. Alt text is set on the image itself, not here.
   */
  image: number | Media;
  /**
   * Optional line under the image, shown to everyone. It does not replace alt text, which is set on the image itself.
   */
  caption?: string | null;
  /**
   * How much of the page the image takes. "Full bleed" fills the whole content area, which is why alignment disappears when you choose it.
   */
  width?: ('narrow' | 'standard' | 'wide' | 'full') | null;
  /**
   * Where a narrower image sits across the page. Center keeps it on the reading axis.
   */
  alignment?: ('center' | 'left' | 'right') | null;
  /**
   * The colour band behind this section. Alternate it with the sections around it.
   */
  background?: ('none' | 'subtle' | 'accent' | 'inverse') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'image';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock".
 */
export interface GalleryBlock {
  /**
   * The line that introduces this section. Leave it blank to run the section without a heading.
   */
  heading?: string | null;
  /**
   * A sentence or two under the heading. Leave it blank to go straight to the content.
   */
  intro?: string | null;
  /**
   * The pictures or logos, in the order you arrange them. Add as many as you have; the layout fits the count.
   */
  items: {
    /**
     * Pick from Media, or upload. Landscape photos sit best in a grid; a logo should be a transparent PNG or SVG so it sits on any background.
     */
    image: number | Media;
    /**
     * Optional line under the image, or a small name under a logo. It also names this row when the list is collapsed.
     */
    caption?: string | null;
    id?: string | null;
  }[];
  /**
   * A grid shows every picture at once and picks its columns from how many there are. A carousel puts them in one swipeable row, roughly one picture wide on a phone and three on a desktop, which suits a long set. Logos draws client or partner logos in gray, turning to full color when a visitor points at one.
   */
  layout?: ('grid' | 'carousel' | 'logos') | null;
  /**
   * The colour band behind this section. Alternate it with the sections around it.
   */
  background?: ('none' | 'subtle' | 'accent' | 'inverse') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'gallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TableBlock".
 */
export interface TableBlock {
  /**
   * The line that introduces this section. Leave it blank to run the section without a heading.
   */
  heading?: string | null;
  /**
   * A sentence or two under the heading. Leave it blank to go straight to the content.
   */
  intro?: string | null;
  /**
   * One row here becomes one column of the table, left to right. Any number: on a narrow screen a wide table scrolls sideways within itself.
   */
  columns: {
    /**
     * e.g. "Localshoring".
     */
    label: string;
    /**
     * Optional smaller line under the column heading.
     */
    tagline?: string | null;
    id?: string | null;
  }[];
  /**
   * One row per thing the columns are compared on.
   */
  rows: {
    /**
     * The label at the start of the row, e.g. "Time zone overlap".
     */
    dimension: string;
    /**
     * One per column, in the same order as the columns above. A row with fewer is padded with blanks; extra cells still show, under no heading.
     */
    cells: {
      /**
       * A few words. Long sentences make the table hard to scan.
       */
      value: string;
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  /**
   * Optional last row, labelled "Best for", saying who each column suits. Same order as the columns above.
   */
  bestForRow?:
    | {
        /**
         * A few words, e.g. "teams that need daylight overlap".
         */
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The colour band behind this section. Alternate it with the sections around it.
   */
  background?: ('none' | 'subtle' | 'accent' | 'inverse') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'table';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AccordionBlock".
 */
export interface AccordionBlock {
  /**
   * The line that introduces this section. Leave it blank to run the section without a heading.
   */
  heading?: string | null;
  /**
   * A sentence or two under the heading. Leave it blank to go straight to the content.
   */
  intro?: string | null;
  /**
   * Accordion stacks closed panels a reader opens one by one: questions and answers, detail most readers skip. Tabs put the titles in a row and show one panel at a time: alternatives a reader compares.
   */
  display: 'accordion' | 'tabs';
  /**
   * For questions, write each the way a prospect would ask it and answer it in the first sentence.
   */
  items: {
    /**
     * The line the reader clicks: a question, or a tab name of a word or two.
     */
    title: string;
    /**
     * What the reader sees once the panel is open.
     */
    body: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    id?: string | null;
  }[];
  /**
   * The colour band behind this section. Alternate it with the sections around it.
   */
  background?: ('none' | 'subtle' | 'accent' | 'inverse') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'accordion';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuoteBlock".
 */
export interface QuoteBlock {
  /**
   * The line that introduces this section. Leave it blank to run the section without a heading.
   */
  heading?: string | null;
  /**
   * A sentence or two under the heading. Leave it blank to go straight to the content.
   */
  intro?: string | null;
  /**
   * A testimonial brings the person’s name, title, company and photo from its record. "Typed here" is for a pull quote with no testimonial behind it, such as a line from a talk or a post. Only the one you pick is published.
   */
  source: 'testimonials' | 'custom';
  /**
   * One testimonial is drawn large. Two or more sit in a grid, in the order you pick them. Add them under Testimonials first.
   */
  testimonials?: (number | Testimonial)[] | null;
  /**
   * The words themselves, without quotation marks. The page adds them.
   */
  quote?: string | null;
  /**
   * Their name. Leave it blank for an unattributed pull quote.
   */
  attribution?: string | null;
  /**
   * Title and organisation, e.g. "CEO, Acme Manufacturing". Shown after the name.
   */
  role?: string | null;
  /**
   * Applies when the block shows a single quote; several always sit in a grid. The photo comes from the testimonial, so a typed quote, or a person with no photo on file, has none and the photo layouts leave it out with the quote left-aligned.
   */
  layout?: ('centered' | 'with-photo-left' | 'with-photo-right') | null;
  /**
   * The colour band behind this section. Alternate it with the sections around it.
   */
  background?: ('none' | 'subtle' | 'accent' | 'inverse') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'quote';
}
/**
 * Client quotes. These have no page of their own; quote blocks pull them onto other pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * The quote itself, without surrounding quotation marks. Keep the words as they said them; trim with an ellipsis rather than rewriting.
   */
  quote: string;
  /**
   * Their full name, as it should appear under the quote.
   */
  personName: string;
  /**
   * For example "VP of Operations". Shown under their name.
   */
  personTitle?: string | null;
  /**
   * Where they work. Only publish it if the client has agreed to be named.
   */
  company?: string | null;
  /**
   * Optional headshot. A testimonial block set to one of the "with photo" layouts falls back to text only when this is empty.
   */
  photo?: (number | null) | Media;
  /**
   * The case study this quote came out of, if there is one.
   */
  caseStudy?: (number | null) | CaseStudy;
  /**
   * Untick to retire a quote without deleting it. Blocks that pull testimonials automatically skip the ones not cleared.
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Client work, listed on /case-studies and pulled onto service and industry pages as proof.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "caseStudies".
 */
export interface CaseStudy {
  id: number;
  /**
   * The result, in a line. Shown on the case study index card and at the top of the study.
   */
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  /**
   * The last part of the web address for this case study, for example "taurex-eticketing". Lowercase words joined by hyphens, no spaces. Changing it on something already published breaks every existing link to it.
   */
  slug: string;
  /**
   * One sentence under the title, on the index card and in search results when the SEO section below is left blank.
   */
  subtitle?: string | null;
  /**
   * What sector the client is in. A "Case studies by industry" block filters on this.
   */
  industry: number | Industry;
  /**
   * Which services this engagement used. A "Case studies by service" block filters on this.
   */
  services?: (number | Service)[] | null;
  /**
   * Who the work was for. Fill in what the client has agreed to have published.
   */
  client?: {
    /**
     * The company name as they write it themselves.
     */
    name?: string | null;
    /**
     * Their mark, for the case study header and logo walls. Transparent background where possible.
     */
    logo?: (number | null) | Media;
    /**
     * Tick when the client has not approved being named. Write around the name in the body too.
     */
    isAnonymized?: boolean | null;
  };
  /**
   * Runs across the top of the case study and appears on the index card. Landscape.
   */
  heroImage: number | Media;
  /**
   * The study itself, built from blocks. A new case study starts from a standard outline; replace the placeholder text in each block.
   */
  layout?:
    | (
        | HeroBlock
        | ContentBlock
        | MediaTextBlock
        | ItemsBlock
        | ImageBlock
        | GalleryBlock
        | TableBlock
        | AccordionBlock
        | QuoteBlock
        | CtaBlock
        | CardsBlock
        | EmbedBlock
        | HubspotFormBlock
      )[]
    | null;
  /**
   * Pick a testimonial already in the panel. Add it to Testimonials first if it is not there.
   */
  testimonial?: (number | null) | Testimonial;
  /**
   * Up to three other studies to offer at the end of this one.
   */
  relatedCaseStudies?: (number | CaseStudy)[] | null;
  /**
   * How this case study looks in a Google result and when someone pastes its link into LinkedIn or Slack. Everything here is optional.
   */
  seo?: {
    /**
     * The blue headline in a Google result. Leave blank to use the case study title above. "| SEQTEK" is appended automatically, so do not type it.
     */
    metaTitle?: string | null;
    /**
     * The gray summary under that headline, and the text on a shared link. Google truncates around 155 characters. Leave blank and the summary line above is used instead.
     */
    metaDescription?: string | null;
    /**
     * The picture that appears when someone shares this link on LinkedIn, Facebook or Slack. Landscape, at least 1200x630. Without one the shared link renders as text only.
     */
    ogImage?: (number | null) | Media;
  };
  /**
   * Orders the case study index, newest first, though it is not shown on the study itself. Leave it blank and the study sorts to the TOP of that index, ahead of everything dated. A date in the future forces this record back to draft, so it will not go live until that date passes and someone publishes it.
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * The markets we sell into, under /industries. Case studies tagged with an industry show up on its page automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries".
 */
export interface Industry {
  id: number;
  /**
   * What this sector is called on case studies and in an industry grid.
   */
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  /**
   * The last part of the web address for this industry, for example "oil-and-gas". Lowercase words joined by hyphens, no spaces. Changing it on something already published breaks every existing link to it.
   */
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  relevantServices?: (number | Service)[] | null;
  clientLogos?:
    | {
        logo: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * The industry page, built from blocks. A new industry starts from a standard outline; replace the placeholder text in each block.
   */
  layout?:
    | (
        | HeroBlock
        | ContentBlock
        | MediaTextBlock
        | ItemsBlock
        | ImageBlock
        | GalleryBlock
        | TableBlock
        | AccordionBlock
        | QuoteBlock
        | CtaBlock
        | CardsBlock
        | EmbedBlock
        | HubspotFormBlock
      )[]
    | null;
  /**
   * How this industry looks in a Google result and when someone pastes its link into LinkedIn or Slack. Everything here is optional.
   */
  seo?: {
    /**
     * The blue headline in a Google result. Leave blank to use the industry title above. "| SEQTEK" is appended automatically, so do not type it.
     */
    metaTitle?: string | null;
    /**
     * The gray summary under that headline, and the text on a shared link. Google truncates around 155 characters. Leave blank and every search result for this collection shows the same generic company tagline, so it is worth writing.
     */
    metaDescription?: string | null;
    /**
     * The picture that appears when someone shares this link on LinkedIn, Facebook or Slack. Landscape, at least 1200x630. Without one the shared link renders as text only.
     */
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * What we sell and how we work, under /services. A top-level menu page holds groups, and a group holds the services themselves.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * A service is the thing a client buys. A group gathers several services and can have its own page. A top-level menu page is what a nav button points at, like "What We Do".
   */
  tier: 'leaf' | 'group' | 'axis';
  /**
   * What this service is called on service cards and case studies.
   */
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  /**
   * The last part of the web address for this service, for example "software-delivery". Lowercase words joined by hyphens, no spaces. Changing it on something already published breaks every existing link to it.
   */
  slug: string;
  /**
   * Leave this blank. There is no icon set behind it yet, so whatever you type is printed on the card as text (ROADMAP INERT-2).
   */
  icon?: string | null;
  /**
   * Case studies that show this service delivered.
   */
  relatedCaseStudies?: (number | CaseStudy)[] | null;
  /**
   * The services shown under this group, in the order you arrange them. The same service may appear under more than one group.
   */
  items?: (number | Service)[] | null;
  /**
   * The service page, built from blocks. Start with a hero so the page has a headline.
   */
  layout?:
    | (
        | HeroBlock
        | ContentBlock
        | MediaTextBlock
        | ItemsBlock
        | ImageBlock
        | GalleryBlock
        | TableBlock
        | AccordionBlock
        | QuoteBlock
        | CtaBlock
        | CardsBlock
        | EmbedBlock
        | HubspotFormBlock
      )[]
    | null;
  /**
   * How this service looks in a Google result and when someone pastes its link into LinkedIn or Slack. Everything here is optional.
   */
  seo?: {
    /**
     * The blue headline in a Google result. Leave blank to use the service title above. "| SEQTEK" is appended automatically, so do not type it.
     */
    metaTitle?: string | null;
    /**
     * The gray summary under that headline, and the text on a shared link. Google truncates around 155 characters. Leave blank and every search result for this collection shows the same generic company tagline, so it is worth writing.
     */
    metaDescription?: string | null;
    /**
     * The picture that appears when someone shares this link on LinkedIn, Facebook or Slack. Landscape, at least 1200x630. Without one the shared link renders as text only.
     */
    ogImage?: (number | null) | Media;
  };
  /**
   * Lowest number first in a service list. Records left without a number come after the numbered ones, newest first.
   */
  order?: number | null;
  /**
   * Scheduling only. A date in the future forces this record back to draft, so it will not go live until that date passes and someone publishes it.
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock".
 */
export interface CtaBlock {
  /**
   * The ask, in a line. Address the reader directly.
   */
  heading: string;
  /**
   * Optional line under the heading. For a download, say what the reader gets: it is what earns the form fill.
   */
  body?: string | null;
  /**
   * Buttons link anywhere. A meeting adds a panel that opens a HubSpot scheduler. Newsletter and download put a HubSpot form in the section; a download hands over the file once the form is sent.
   */
  action: 'buttons' | 'meeting' | 'newsletter' | 'download';
  /**
   * Centered stacks everything down the middle. Split puts the heading on the left and the buttons, scheduler, form or download beside it; on a phone the two stack.
   */
  variant: 'centered' | 'split';
  /**
   * The action this section exists to get. Required for "Click a button"; optional beside a scheduler.
   */
  primaryCta?: {
    /**
     * The words on the button. Two to four words reads best, e.g. "Book a call".
     */
    label?: string | null;
    /**
     * Where the button goes. A path on this site starts with a slash ("/contact"); an outside link needs the full https:// address.
     */
    url?: string | null;
    /**
     * How much weight the button carries: solid for the one thing you want clicked, outlined for a real but lesser option, text-only when it should not compete with the page.
     */
    variant?: ('primary' | 'secondary' | 'ghost') | null;
  };
  /**
   * Optional lighter alternative, drawn as a plain link, e.g. emailing instead of booking.
   */
  secondaryCta?: {
    /**
     * The words on the button. Two to four words reads best, e.g. "Book a call".
     */
    label?: string | null;
    /**
     * Where the button goes. A path on this site starts with a slash ("/contact"); an outside link needs the full https:// address.
     */
    url?: string | null;
  };
  /**
   * A HubSpot meetings address, e.g. https://meetings.hubspot.com/name. The panel's "See available times" button opens it in a new tab.
   */
  meetingUrl?: string | null;
  /**
   * The HubSpot form ID (Marketing > Forms > Share > embed code), e.g. 12345678-90ab-cdef-1234-567890abcdef. A newsletter sends an email address to it; a download sends name, email and company.
   */
  formId?: string | null;
  /**
   * A picture of the thing itself, e.g. the report cover. Portrait or square reads best.
   */
  coverImage?: (number | null) | Media;
  /**
   * The full https:// address of the file. The form hides it from the page, but it is still present in the page source, so treat this as a public link: the form is a courtesy step most people will take, not a lock. Do not put anything here you would not publish outright.
   */
  fileUrl?: string | null;
  /**
   * The colour band behind this section. Alternate it with the sections around it.
   */
  background?: ('none' | 'subtle' | 'accent' | 'inverse' | 'brand') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardsBlock".
 */
export interface CardsBlock {
  /**
   * The line that introduces this section. Leave it blank to run the section without a heading.
   */
  heading?: string | null;
  /**
   * A sentence or two under the heading. Leave it blank to go straight to the content.
   */
  intro?: string | null;
  /**
   * The kind of thing this section lists. Each draws as its own card: a case study with its photo, a person with their headshot, a market by name. If nothing matches, the whole section is left off the page, heading included.
   */
  collection:
    'caseStudies' | 'posts' | 'services' | 'industries' | 'workshops' | 'teamMembers' | 'locations' | 'partners';
  /**
   * "All of them" and "Filtered" fill themselves in and stay current as you publish. "Pick them by hand" shows exactly the items you choose below, in your order. Case studies, insights, services and team members can be filtered; for anything else, "Filtered" lists all of them.
   */
  source: 'all' | 'filtered' | 'manual';
  /**
   * Shows the case studies whose client is in this sector. Leave it blank to skip this filter.
   */
  industry?: (number | null) | Industry;
  /**
   * Shows the case studies where we delivered this service. Leave it blank to skip this filter; set both and a study must match both.
   */
  service?: (number | null) | Service;
  /**
   * Shows the insights filed under this topic, newest first.
   */
  category?: (number | null) | Category;
  /**
   * Tick to show only the people marked as leadership. Leave it clear to show the whole team, leadership first.
   */
  leadershipOnly?: boolean | null;
  /**
   * Shows the services this group holds, in the order the group arranges them.
   */
  serviceGroup?: (number | null) | Service;
  /**
   * The exact items, in the order you pick them. Switch "What to list" and anything picked from the old kind is ignored.
   */
  manualItems?:
    | (
        | {
            relationTo: 'caseStudies';
            value: number | CaseStudy;
          }
        | {
            relationTo: 'posts';
            value: number | Post;
          }
        | {
            relationTo: 'services';
            value: number | Service;
          }
        | {
            relationTo: 'industries';
            value: number | Industry;
          }
        | {
            relationTo: 'workshops';
            value: number | Workshop;
          }
        | {
            relationTo: 'teamMembers';
            value: number | TeamMember;
          }
        | {
            relationTo: 'locations';
            value: number | Location;
          }
        | {
            relationTo: 'partners';
            value: number | Partner;
          }
      )[]
    | null;
  /**
   * Stops the list after this many, whichever way it is filled. Leave it blank to show all of them.
   */
  limit?: number | null;
  /**
   * "Grid" draws every item as an equal card. "First one featured" draws the first item large, beside its picture, with the rest as a grid underneath.
   */
  display: 'grid' | 'featured';
  /**
   * The colour band behind this section. Alternate it with the sections around it.
   */
  background?: ('none' | 'subtle' | 'accent' | 'inverse') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cards';
}
/**
 * Tags for articles. They group posts on /insights and drive the related-reading links.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * What this topic is called on a post and in a "Posts by category" block.
   */
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  /**
   * The last part of the web address for this topic, for example "delivery". Lowercase words joined by hyphens, no spaces. Changing it on something already published breaks every existing link to it.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Articles listed on /insights. Written as flowing text rather than blocks, with a category and a published date.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  /**
   * The title of the post, as it appears on the insights index and the post itself.
   */
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  /**
   * The last part of the web address for this post, for example "why-localshoring-works". Lowercase words joined by hyphens, no spaces. Changing it on something already published breaks every existing link to it.
   */
  slug: string;
  /**
   * One or two sentences shown on the insights index card, and used as the search result summary when the SEO section below is left blank.
   */
  excerpt?: string | null;
  /**
   * The article. Use the slash menu to drop in a callout, a pull quote or an image between paragraphs.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Runs across the top of the post and appears on the insights index card. Landscape.
   */
  featuredImage: number | Media;
  /**
   * Shown as the byline. Pick from the team members already in the panel.
   */
  author: number | TeamMember;
  /**
   * What this post is about. Topics are how a "Posts by category" block finds it.
   */
  categories?: (number | Category)[] | null;
  /**
   * Used to connect the post to the work it describes. Not shown on the post itself.
   */
  relatedServices?: (number | Service)[] | null;
  /**
   * How this post looks in a Google result and when someone pastes its link into LinkedIn or Slack. Everything here is optional.
   */
  seo?: {
    /**
     * The blue headline in a Google result. Leave blank to use the post title above. "| SEQTEK" is appended automatically, so do not type it.
     */
    metaTitle?: string | null;
    /**
     * The gray summary under that headline, and the text on a shared link. Google truncates around 155 characters. Leave blank and the summary above is used instead.
     */
    metaDescription?: string | null;
    /**
     * The picture that appears when someone shares this link on LinkedIn, Facebook or Slack. Landscape, at least 1200x630. Without one the shared link renders as text only.
     */
    ogImage?: (number | null) | Media;
  };
  /**
   * Orders the insights index, newest first, and is the date shown on the post itself. Leave it blank and the post sorts to the TOP of that index, ahead of everything dated. A date in the future forces this record back to draft, so it will not go live until that date passes and someone publishes it.
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * The people shown on /team. Leadership is flagged separately and sorts to the top.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teamMembers".
 */
export interface TeamMember {
  id: number;
  /**
   * The name as this person writes it. Heads their card and their own page.
   */
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  /**
   * The last part of the web address for this profile, for example "dana-dudley". Lowercase words joined by hyphens, no spaces. Changing it on something already published breaks every existing link to it.
   */
  slug: string;
  /**
   * The short job title, as it appears on the team cards — for example "CTO" or "Enterprise Architect". Leave it blank and the card shows only the name.
   */
  title?: string | null;
  /**
   * A full sentence describing what this person owns. It appears only on their own /team page, under the job title — never on the cards. Leave it blank if the job title says enough.
   */
  role?: string | null;
  /**
   * Landscape reads best: the cards crop it to 4:3 and the photo fills the top of the card. The compact team layout crops the same file to a circle instead.
   */
  photo: number | Media;
  /**
   * This person's own page, built from blocks. A new profile starts from a standard outline; replace the placeholder text in each block.
   */
  layout?:
    | (
        | HeroBlock
        | ContentBlock
        | MediaTextBlock
        | ItemsBlock
        | ImageBlock
        | GalleryBlock
        | TableBlock
        | AccordionBlock
        | QuoteBlock
        | CtaBlock
        | CardsBlock
        | EmbedBlock
        | HubspotFormBlock
      )[]
    | null;
  /**
   * The full https:// address of their LinkedIn page. Becomes the LinkedIn icon on their profile; leave blank and no icon is drawn.
   */
  linkedinUrl?: string | null;
  /**
   * Published on their profile as a contact link, so use the address they are happy to have public.
   */
  email?: string | null;
  /**
   * Tick to include this person when a team block is set to show leadership only.
   */
  isLeadership?: boolean | null;
  /**
   * Lowest number first in the team grid, after the leadership members. Records left without a number come after the numbered ones, newest first.
   */
  order?: number | null;
  /**
   * Short skill or subject labels, one per row (for example "Cloud architecture", "Team facilitation"). These do not appear on the page, but search engines and AI assistants read them to understand what this person is known for.
   */
  expertise?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * How this profile looks in a Google result and when someone pastes its link into LinkedIn or Slack. Everything here is optional.
   */
  seo?: {
    /**
     * The blue headline in a Google result. Leave blank to use the profile title above. "| SEQTEK" is appended automatically, so do not type it.
     */
    metaTitle?: string | null;
    /**
     * The gray summary under that headline, and the text on a shared link. Google truncates around 155 characters. Leave blank and every search result for this collection shows the same generic company tagline, so it is worth writing.
     */
    metaDescription?: string | null;
    /**
     * The picture that appears when someone shares this link on LinkedIn, Facebook or Slack. Landscape, at least 1200x630. Without one the shared link renders as text only.
     */
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EmbedBlock".
 */
export interface EmbedBlock {
  /**
   * A YouTube or Vimeo video, a map from OpenStreetMap or Google Maps, or any other web page that allows being shown inside another site. The fields below change to match.
   */
  kind: 'video' | 'map' | 'page';
  /**
   * The line that introduces this section. Leave it blank to run the section without a heading.
   */
  heading?: string | null;
  /**
   * Shown only for a video. The small line above it, e.g. "From the podcast". Marks the video as a deliberate interlude rather than decoration.
   */
  eyebrow?: string | null;
  /**
   * Names the video, map or page for screen readers, e.g. "Workshop recap" or "Map of our Tulsa office". Not drawn on screen. For a video, use its real title.
   */
  title: string;
  /**
   * Shown only for a video. Which service to embed from; it decides how the ID below is read.
   */
  provider?: ('youtube' | 'vimeo') | null;
  /**
   * Shown only for a video. Just the ID, not the whole address. On YouTube it is the part after "v=" (dQw4w9WgXcQ); on Vimeo it is the digits at the end of the address.
   */
  videoId?: string | null;
  /**
   * Shown only for a video, and optional. With one set, the page shows this still and a Play button, and loads the video only when a reader clicks it, which keeps YouTube or Vimeo from tracking people who never watch. Leave it blank to embed the player directly.
   */
  thumbnail?: (number | null) | Media;
  /**
   * Shown only for a map or a web page. The full https:// address to show in the frame. For a map, use the embed address from OpenStreetMap or Google Maps ("Share > Embed a map", then copy the src address); other map hosts are refused and the block shows a notice instead. A web page must allow embedding, and many sites refuse.
   */
  url?: string | null;
  /**
   * Shown only for a map or a web page, and optional. A visible line under the frame, e.g. the street address.
   */
  caption?: string | null;
  /**
   * Shown only for a map or a web page. How tall the frame is; a longer page scrolls inside it. Short suits a map, tall a form or a dashboard.
   */
  height?: ('short' | 'medium' | 'tall') | null;
  /**
   * The colour band behind this section. Alternate it with the sections around it.
   */
  background?: ('none' | 'subtle' | 'accent' | 'inverse') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'embed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HubspotFormBlock".
 */
export interface HubspotFormBlock {
  /**
   * The line that introduces this section. Leave it blank to run the section without a heading.
   */
  heading?: string | null;
  /**
   * Optional line above the form saying what happens after they submit it.
   */
  description?: string | null;
  /**
   * Which HubSpot form to embed. Copy the form ID out of HubSpot (Marketing > Forms > Share > embed code); it looks like 12345678-90ab-cdef-1234-567890abcdef.
   */
  formId: string;
  /**
   * The colour band behind this section. Alternate it with the sections around it.
   */
  background?: ('none' | 'subtle' | 'accent' | 'inverse') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hubspot-form';
}
/**
 * Workshop landing pages under /workshops, each with its own registration form.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workshops".
 */
export interface Workshop {
  id: number;
  /**
   * What this workshop is called, on the workshops index and its own page.
   */
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  /**
   * The last part of the web address for this workshop, for example "ai-readiness". Lowercase words joined by hyphens, no spaces. Changing it on something already published breaks every existing link to it.
   */
  slug: string;
  /**
   * The workshop page, built from blocks. A new workshop starts from a standard outline; replace the placeholder text in each block.
   */
  layout?:
    | (
        | HeroBlock
        | ContentBlock
        | MediaTextBlock
        | ItemsBlock
        | ImageBlock
        | GalleryBlock
        | TableBlock
        | AccordionBlock
        | QuoteBlock
        | CtaBlock
        | CardsBlock
        | EmbedBlock
        | HubspotFormBlock
      )[]
    | null;
  /**
   * The team member who leads this workshop.
   */
  facilitator?: (number | null) | TeamMember;
  /**
   * Pick a testimonial already in the panel. Add it to Testimonials first if it is not there.
   */
  testimonial?: (number | null) | Testimonial;
  /**
   * Lowest number first in the /workshops page (a workshop-list block keeps the order you pick there). Records left without a number come after the numbered ones, newest first.
   */
  order?: number | null;
  /**
   * How this workshop looks in a Google result and when someone pastes its link into LinkedIn or Slack. Everything here is optional.
   */
  seo?: {
    /**
     * The blue headline in a Google result. Leave blank to use the workshop title above. "| SEQTEK" is appended automatically, so do not type it.
     */
    metaTitle?: string | null;
    /**
     * The gray summary under that headline, and the text on a shared link. Google truncates around 155 characters. Leave blank and every search result for this collection shows the same generic company tagline, so it is worth writing.
     */
    metaDescription?: string | null;
    /**
     * The picture that appears when someone shares this link on LinkedIn, Facebook or Slack. Landscape, at least 1200x630. Without one the shared link renders as text only.
     */
    ogImage?: (number | null) | Media;
  };
  /**
   * Scheduling only. A date in the future forces this record back to draft, so it will not go live until that date passes and someone publishes it.
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * The markets we serve. Nothing on the site reads these yet, so editing one changes nothing a visitor sees.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  /**
   * The market name, as it appears on a "Where we work" block.
   */
  city: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  /**
   * The last part of the web address for this market, for example "tulsa". Lowercase words joined by hyphens, no spaces. Changing it on something already published breaks every existing link to it.
   */
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  address?: {
    street?: string | null;
    city?: string | null;
    state?: string | null;
    zip?: string | null;
  };
  hasOffice?: boolean | null;
  /**
   * How this location looks in a Google result and when someone pastes its link into LinkedIn or Slack. Everything here is optional.
   */
  seo?: {
    /**
     * The blue headline in a Google result. Leave blank to use the location title above. "| SEQTEK" is appended automatically, so do not type it.
     */
    metaTitle?: string | null;
    /**
     * The gray summary under that headline, and the text on a shared link. Google truncates around 155 characters. Leave blank and every search result for this collection shows the same generic company tagline, so it is worth writing.
     */
    metaDescription?: string | null;
    /**
     * The picture that appears when someone shares this link on LinkedIn, Facebook or Slack. Landscape, at least 1200x630. Without one the shared link renders as text only.
     */
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Technology and delivery partners, shown on /partners.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  /**
   * The partner company name, as they write it themselves.
   */
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  /**
   * The last part of the web address for this partner, for example "microsoft". Lowercase words joined by hyphens, no spaces. Changing it on something already published breaks every existing link to it.
   */
  slug: string;
  /**
   * One or two sentences on what we do together, shown on the partners index card. It does not reach search results: fill in the summary below for that.
   */
  summary?: string | null;
  /**
   * The partner's own mark, for the index card. Transparent PNG or SVG where possible.
   */
  logo: number | Media;
  /**
   * The partner's own website, as a full https:// address. Rendered as a link that opens off this site.
   */
  url?: string | null;
  /**
   * The partner page, built from blocks. A new partner starts from a standard outline; replace the placeholder text in each block.
   */
  layout?:
    | (
        | HeroBlock
        | ContentBlock
        | MediaTextBlock
        | ItemsBlock
        | ImageBlock
        | GalleryBlock
        | TableBlock
        | AccordionBlock
        | QuoteBlock
        | CtaBlock
        | CardsBlock
        | EmbedBlock
        | HubspotFormBlock
      )[]
    | null;
  /**
   * Lowest number first in the partner list. Partners without a number come after the numbered ones, in alphabetical order.
   */
  order?: number | null;
  /**
   * Scheduling only. A date in the future forces this record back to draft, so it will not go live until that date passes and someone publishes it.
   */
  publishedAt?: string | null;
  /**
   * How this partner looks in a Google result and when someone pastes its link into LinkedIn or Slack. Everything here is optional.
   */
  seo?: {
    /**
     * The blue headline in a Google result. Leave blank to use the partner title above. "| SEQTEK" is appended automatically, so do not type it.
     */
    metaTitle?: string | null;
    /**
     * The gray summary under that headline, and the text on a shared link. Google truncates around 155 characters. Leave blank and every search result for this collection shows the same generic company tagline, so it is worth writing.
     */
    metaDescription?: string | null;
    /**
     * The picture that appears when someone shares this link on LinkedIn, Facebook or Slack. Landscape, at least 1200x630. Without one the shared link renders as text only.
     */
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * The buttons across the top of every page, in order, and the dropdown under each one. Changes here go live on publish, without a deploy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * The words on the button itself, for example "What We Do". This one is not optional: a top-level button is named by the menu rather than by whatever it points at.
   */
  label: string;
  /**
   * Every top-level button is a link as well as a menu, so the page behind it is never stranded behind a dropdown.
   */
  link: {
    /**
     * Pick a page on this site wherever you can, so the link follows the page if its address changes.
     */
    type: 'internal' | 'external';
    /**
     * Start typing to find a published page. Only published pages are listed: the menu is not allowed to point at something a visitor cannot open.
     */
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'services';
          value: number | Service;
        } | null)
      | ({
          relationTo: 'workshops';
          value: number | Workshop;
        } | null)
      | ({
          relationTo: 'industries';
          value: number | Industry;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'caseStudies';
          value: number | CaseStudy;
        } | null)
      | ({
          relationTo: 'partners';
          value: number | Partner;
        } | null);
    /**
     * A full address including https://. Use this only for somewhere off this site — anything on seqtek.com should be picked as a page above.
     */
    url?: string | null;
  };
  /**
   * Leave this empty for a plain button with no dropdown. One row per column: one column gives a simple list, several draw side by side.
   */
  groups?:
    | {
        /**
         * The heading over this column. With only one column it is not drawn at all — the button above is already the heading.
         */
        label: string;
        /**
         * A column heading may be a link to a page of its own, or just a heading. Choose "just a heading" when there is no page to send people to.
         */
        link: {
          /**
           * Pick a page on this site wherever you can, so the link follows the page if its address changes. A heading is a column title with nothing to click.
           */
          type: 'internal' | 'external' | 'heading';
          /**
           * Start typing to find a published page. Only published pages are listed: the menu is not allowed to point at something a visitor cannot open.
           */
          doc?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'services';
                value: number | Service;
              } | null)
            | ({
                relationTo: 'workshops';
                value: number | Workshop;
              } | null)
            | ({
                relationTo: 'industries';
                value: number | Industry;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'caseStudies';
                value: number | CaseStudy;
              } | null)
            | ({
                relationTo: 'partners';
                value: number | Partner;
              } | null);
          /**
           * A full address including https://. Use this only for somewhere off this site — anything on seqtek.com should be picked as a page above.
           */
          url?: string | null;
        };
        items?:
          | {
              /**
               * One entry in the column, in the order you arrange them.
               */
              link: {
                /**
                 * Pick a page on this site wherever you can, so the link follows the page if its address changes.
                 */
                type: 'internal' | 'external';
                /**
                 * Start typing to find a published page. Only published pages are listed: the menu is not allowed to point at something a visitor cannot open.
                 */
                doc?:
                  | ({
                      relationTo: 'pages';
                      value: number | Page;
                    } | null)
                  | ({
                      relationTo: 'services';
                      value: number | Service;
                    } | null)
                  | ({
                      relationTo: 'workshops';
                      value: number | Workshop;
                    } | null)
                  | ({
                      relationTo: 'industries';
                      value: number | Industry;
                    } | null)
                  | ({
                      relationTo: 'posts';
                      value: number | Post;
                    } | null)
                  | ({
                      relationTo: 'caseStudies';
                      value: number | CaseStudy;
                    } | null)
                  | ({
                      relationTo: 'partners';
                      value: number | Partner;
                    } | null);
                /**
                 * A full address including https://. Use this only for somewhere off this site — anything on seqtek.com should be picked as a page above.
                 */
                url?: string | null;
                /**
                 * For a page on this site: leave blank to use the page's own title, so renaming the page renames the menu. For a web address: required — there is no page title to borrow, and leaving it blank drops the link from the menu.
                 */
                label?: string | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Lowest number first in the row of buttons, left to right. Buttons without a number come after the numbered ones, in alphabetical order.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Who can sign in to this panel, and what each of them is allowed to do.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Shown wherever this account appears in the panel.
   */
  name: string;
  /**
   * Editors can create, edit and publish content. Admins can do that, and can also delete records and change access here. Accounts themselves are created by signing in with Google, never in this panel.
   */
  roles: ('admin' | 'editor')[];
  /**
   * Stable identifier from Google. Set on first sign-in; never edited.
   */
  googleSub?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'caseStudies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'industries';
        value: number | Industry;
      } | null)
    | ({
        relationTo: 'workshops';
        value: number | Workshop;
      } | null)
    | ({
        relationTo: 'teamMembers';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'navigation';
        value: number | Navigation;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  publishedAt?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        'media-text'?: T | MediaTextBlockSelect<T>;
        items?: T | ItemsBlockSelect<T>;
        image?: T | ImageBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        table?: T | TableBlockSelect<T>;
        accordion?: T | AccordionBlockSelect<T>;
        quote?: T | QuoteBlockSelect<T>;
        cta?: T | CtaBlockSelect<T>;
        cards?: T | CardsBlockSelect<T>;
        embed?: T | EmbedBlockSelect<T>;
        'hubspot-form'?: T | HubspotFormBlockSelect<T>;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  variant?: T;
  eyebrow?: T;
  headline?: T;
  subheadline?: T;
  media?: T;
  videoUrl?: T;
  primaryCta?:
    | T
    | {
        label?: T;
        url?: T;
        variant?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        url?: T;
      };
  alignment?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  width?: T;
  body?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaTextBlock_select".
 */
export interface MediaTextBlockSelect<T extends boolean = true> {
  media?: T;
  mediaPosition?: T;
  body?: T;
  cta?:
    | T
    | {
        label?: T;
        url?: T;
      };
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ItemsBlock_select".
 */
export interface ItemsBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  layout?: T;
  markers?: T;
  style?: T;
  items?:
    | T
    | {
        title?: T;
        body?: T;
        marker?: T;
        image?: T;
        link?:
          | T
          | {
              label?: T;
              url?: T;
            };
        id?: T;
      };
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlock_select".
 */
export interface ImageBlockSelect<T extends boolean = true> {
  image?: T;
  caption?: T;
  width?: T;
  alignment?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock_select".
 */
export interface GalleryBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  items?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  layout?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TableBlock_select".
 */
export interface TableBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  columns?:
    | T
    | {
        label?: T;
        tagline?: T;
        id?: T;
      };
  rows?:
    | T
    | {
        dimension?: T;
        cells?:
          | T
          | {
              value?: T;
              id?: T;
            };
        id?: T;
      };
  bestForRow?:
    | T
    | {
        value?: T;
        id?: T;
      };
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AccordionBlock_select".
 */
export interface AccordionBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  display?: T;
  items?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuoteBlock_select".
 */
export interface QuoteBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  source?: T;
  testimonials?: T;
  quote?: T;
  attribution?: T;
  role?: T;
  layout?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock_select".
 */
export interface CtaBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  action?: T;
  variant?: T;
  primaryCta?:
    | T
    | {
        label?: T;
        url?: T;
        variant?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        url?: T;
      };
  meetingUrl?: T;
  formId?: T;
  coverImage?: T;
  fileUrl?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardsBlock_select".
 */
export interface CardsBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  collection?: T;
  source?: T;
  industry?: T;
  service?: T;
  category?: T;
  leadershipOnly?: T;
  serviceGroup?: T;
  manualItems?: T;
  limit?: T;
  display?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EmbedBlock_select".
 */
export interface EmbedBlockSelect<T extends boolean = true> {
  kind?: T;
  heading?: T;
  eyebrow?: T;
  title?: T;
  provider?: T;
  videoId?: T;
  thumbnail?: T;
  url?: T;
  caption?: T;
  height?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HubspotFormBlock_select".
 */
export interface HubspotFormBlockSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  formId?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  author?: T;
  categories?: T;
  relatedServices?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "caseStudies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  subtitle?: T;
  industry?: T;
  services?: T;
  client?:
    | T
    | {
        name?: T;
        logo?: T;
        isAnonymized?: T;
      };
  heroImage?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        'media-text'?: T | MediaTextBlockSelect<T>;
        items?: T | ItemsBlockSelect<T>;
        image?: T | ImageBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        table?: T | TableBlockSelect<T>;
        accordion?: T | AccordionBlockSelect<T>;
        quote?: T | QuoteBlockSelect<T>;
        cta?: T | CtaBlockSelect<T>;
        cards?: T | CardsBlockSelect<T>;
        embed?: T | EmbedBlockSelect<T>;
        'hubspot-form'?: T | HubspotFormBlockSelect<T>;
      };
  testimonial?: T;
  relatedCaseStudies?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  tier?: T;
  title?: T;
  generateSlug?: T;
  slug?: T;
  icon?: T;
  relatedCaseStudies?: T;
  items?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        'media-text'?: T | MediaTextBlockSelect<T>;
        items?: T | ItemsBlockSelect<T>;
        image?: T | ImageBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        table?: T | TableBlockSelect<T>;
        accordion?: T | AccordionBlockSelect<T>;
        quote?: T | QuoteBlockSelect<T>;
        cta?: T | CtaBlockSelect<T>;
        cards?: T | CardsBlockSelect<T>;
        embed?: T | EmbedBlockSelect<T>;
        'hubspot-form'?: T | HubspotFormBlockSelect<T>;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  order?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries_select".
 */
export interface IndustriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  description?: T;
  relevantServices?: T;
  clientLogos?:
    | T
    | {
        logo?: T;
        id?: T;
      };
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        'media-text'?: T | MediaTextBlockSelect<T>;
        items?: T | ItemsBlockSelect<T>;
        image?: T | ImageBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        table?: T | TableBlockSelect<T>;
        accordion?: T | AccordionBlockSelect<T>;
        quote?: T | QuoteBlockSelect<T>;
        cta?: T | CtaBlockSelect<T>;
        cards?: T | CardsBlockSelect<T>;
        embed?: T | EmbedBlockSelect<T>;
        'hubspot-form'?: T | HubspotFormBlockSelect<T>;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workshops_select".
 */
export interface WorkshopsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        'media-text'?: T | MediaTextBlockSelect<T>;
        items?: T | ItemsBlockSelect<T>;
        image?: T | ImageBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        table?: T | TableBlockSelect<T>;
        accordion?: T | AccordionBlockSelect<T>;
        quote?: T | QuoteBlockSelect<T>;
        cta?: T | CtaBlockSelect<T>;
        cards?: T | CardsBlockSelect<T>;
        embed?: T | EmbedBlockSelect<T>;
        'hubspot-form'?: T | HubspotFormBlockSelect<T>;
      };
  facilitator?: T;
  testimonial?: T;
  order?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teamMembers_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  title?: T;
  role?: T;
  photo?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        'media-text'?: T | MediaTextBlockSelect<T>;
        items?: T | ItemsBlockSelect<T>;
        image?: T | ImageBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        table?: T | TableBlockSelect<T>;
        accordion?: T | AccordionBlockSelect<T>;
        quote?: T | QuoteBlockSelect<T>;
        cta?: T | CtaBlockSelect<T>;
        cards?: T | CardsBlockSelect<T>;
        embed?: T | EmbedBlockSelect<T>;
        'hubspot-form'?: T | HubspotFormBlockSelect<T>;
      };
  linkedinUrl?: T;
  email?: T;
  isLeadership?: T;
  order?: T;
  expertise?:
    | T
    | {
        label?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  summary?: T;
  logo?: T;
  url?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        'media-text'?: T | MediaTextBlockSelect<T>;
        items?: T | ItemsBlockSelect<T>;
        image?: T | ImageBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        table?: T | TableBlockSelect<T>;
        accordion?: T | AccordionBlockSelect<T>;
        quote?: T | QuoteBlockSelect<T>;
        cta?: T | CtaBlockSelect<T>;
        cards?: T | CardsBlockSelect<T>;
        embed?: T | EmbedBlockSelect<T>;
        'hubspot-form'?: T | HubspotFormBlockSelect<T>;
      };
  order?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        mobile_webp?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        mobile_jpeg?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet_webp?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet_jpeg?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        desktop_webp?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        desktop_jpeg?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide_webp?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide_jpeg?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  label?: T;
  link?:
    | T
    | {
        type?: T;
        doc?: T;
        url?: T;
      };
  groups?:
    | T
    | {
        label?: T;
        link?:
          | T
          | {
              type?: T;
              doc?: T;
              url?: T;
            };
        items?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    doc?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  personName?: T;
  personTitle?: T;
  company?: T;
  photo?: T;
  caseStudy?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  city?: T;
  generateSlug?: T;
  slug?: T;
  description?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        zip?: T;
      };
  hasOffice?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  googleSub?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * The homepage at /, built from blocks. There is only one of it, so it is edited here instead of in a list.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  /**
   * The homepage, built from blocks, top to bottom. Add a block for each band of the page; drag the handles to reorder.
   */
  layout?:
    | (
        | HeroBlock
        | ContentBlock
        | MediaTextBlock
        | ItemsBlock
        | ImageBlock
        | GalleryBlock
        | TableBlock
        | AccordionBlock
        | QuoteBlock
        | CtaBlock
        | CardsBlock
        | EmbedBlock
        | HubspotFormBlock
      )[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        'media-text'?: T | MediaTextBlockSelect<T>;
        items?: T | ItemsBlockSelect<T>;
        image?: T | ImageBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        table?: T | TableBlockSelect<T>;
        accordion?: T | AccordionBlockSelect<T>;
        quote?: T | QuoteBlockSelect<T>;
        cta?: T | CtaBlockSelect<T>;
        cards?: T | CardsBlockSelect<T>;
        embed?: T | EmbedBlockSelect<T>;
        'hubspot-form'?: T | HubspotFormBlockSelect<T>;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CalloutBlock".
 */
export interface CalloutBlock {
  /**
   * Sets the color of the panel. Warning is the loudest, so save it for something a reader would regret missing.
   */
  tone: 'info' | 'tip' | 'warning' | 'note';
  /**
   * A sentence or two set apart from the surrounding paragraphs.
   */
  body: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'callout';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageWithCaptionBlock".
 */
export interface ImageWithCaptionBlock {
  /**
   * Pick from Media, or upload. Alt text is set on the image itself, not here.
   */
  image: number | Media;
  /**
   * Optional line under the image, shown to everyone.
   */
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'image-with-caption';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FigureBlock".
 */
export interface FigureBlock {
  /**
   * Pick from Media, or upload. Alt text is set on the image itself, not here.
   */
  image: number | Media;
  /**
   * Required here, because this block exists for images that need explaining. Use the plain image block instead when there is nothing to say.
   */
  caption: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'figure';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuotePullquoteBlock".
 */
export interface QuotePullquoteBlock {
  /**
   * The line to lift out of the surrounding text, without quotation marks. It is set large, so keep it to a sentence or two.
   */
  quote: string;
  /**
   * Optional name and title under the quote. Leave blank when lifting a line from the article itself.
   */
  attribution?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'quote-pullquote';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialEmbedBlock".
 */
export interface TestimonialEmbedBlock {
  /**
   * Pick a testimonial already in the panel. Add it under Testimonials first if it is not there.
   */
  testimonial: number | Testimonial;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonial-embed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DisclosureBlock".
 */
export interface DisclosureBlock {
  /**
   * The line the reader sees and clicks to open, e.g. "How we price this".
   */
  summary: string;
  /**
   * What appears when it is opened. It starts closed, so nothing essential should live only in here.
   */
  body: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'disclosure';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InlineCtaBlock".
 */
export interface InlineCtaBlock {
  /**
   * The words the reader clicks. Two to four words reads best.
   */
  label: string;
  /**
   * Where the button goes. A page on this site starts with a slash ("/contact"); an outside link needs the full https:// address.
   */
  url: string;
  /**
   * How the link is drawn. All four are underlined: primary is bold and accent-colored, secondary is muted, and ghost and link are plain body text.
   */
  variant?: ('primary' | 'secondary' | 'ghost' | 'link') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'inline-cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}